apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

helmCharts:
- name: external-dns
  releaseName: external-dns
  namespace: kube-system
  version: 1.3.0
  repo: https://kubernetes-sigs.github.io/external-dns/
